spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5433/userservice
    username: ${DB_USERNAME:hobbybobby}
    password: ${DB_PASSWORD:hobbybobby}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 9002
